; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.5
	https://github.com/dancol90/ESP8266Ping.git

[env:wemos_d1_r1]
platform = espressif8266
board = d1
framework = arduino
upload_speed = 115200
monitor_speed = 115200
lib_deps = ${common.lib_deps}
platform_packages = platformio/tool-scons@^4.40801.0

[env:nodemcu_1_0]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 115200
monitor_speed = 115200
lib_deps = ${common.lib_deps}
platform_packages = platformio/tool-scons@^4.40801.0


